### ISSUE TITLE
Small requests are encoded in Base64

### ISSUE THREAD

**Issue by AlexMog** [vendia/serverless-express#266]
Hello,  
I was working on an API with small answers and large answers.  
I've used the base found in https://github.com/awslabs/aws-serverless-express/blob/master/examples/basic-starter/lambda.js for my lambda entrypoint.  
I wasn't using the "binaryMimeType" at first, So I hadn't any problems.  
But I got some "ERR_CONTENT_DECODING_FAILED" errors, because I have generated bigger requests (so, I imagine, some compression is made ?), so I reactivated BinaryMimeTypes, BUT, now, my small answers are encoded in Base64 and never decoded by the APIGateway (so my client recieves Base64 encoded stuff)...  
How can I fix this ? Is this a bug or it is fixable ?

Thanks !

**Comment by marracuene** [comment]
https://github.com/awslabs/aws-serverless-express/issues/307 explains how to use the binaryMimeTypes array when preparing the server.          When setting this array to include 'application/json', with compression activated on the server, I found that all JSON responses below the compression size limit were Base64Encoded.     Removing 'application/json' some of these responses were now returned without Base64Encoding (i.e. expected behaviour).   Whereas others were not.    Seems like somewhere these responses are still being treated as binary, despite having `content-type: application/json` in response header.
<p/>
I attempted to reproduce this locally with "pure" express inside node.js, and everything works perfectly - i.e. the compression middleware compresses what it should, and leaves everything else alone.    So it does seem to be a problem in aws-serverless-express .

Looking through the source I would imagine that the problem starts in [index.js](https://github.com/awslabs/aws-serverless-express/blob/master/src/index.js), the lines below...    However looking at the calls and implementations of getContentType and isContentTypeBinaryMimeType they seem perfectly sensible?    So perhaps the content-type is not set at the time these calls are made?         
```
 const contentType = getContentType({ contentTypeHeader: headers['content-type'] })
 const isBase64Encoded = isContentTypeBinaryMimeType({ contentType, binaryMimeTypes: server._binaryTypes })
```

**Comment by marracuene** [comment]
After reading https://github.com/awslabs/aws-serverless-express/issues/271 , tried porting to https://github.com/dougmoscrop/serverless-http and it does not have this problem.   Also seems to be a bit faster but did not test that systematically.

**Comment by isunli** [comment]
same issue here, a simple work around is just delete the compression middleware and delete application/json from mimeType
